window.TA_DATA = {
  "updated": "2026-07-21 22:36:35",
  "symbol": "XAUUSD",
  "timeframe": "",
  "signals": [
    {
      "time": "2026-07-21 22:36:35",
      "candle_time": "2026-07-01 12:00:00",
      "symbol": "XAUUSD",
      "timeframe": "M15",
      "action": "BUY",
      "trend": "UPTREND",
      "strength": "STRONG",
      "price": 101.0,
      "ema20": 100.8,
      "ema50": 100.0,
      "ema200": 98.0,
      "adx": 30.0,
      "atr": 1.0,
      "rsi": 58.0,
      "pattern": "Bullish Engulfing",
      "reason": "HTF UPTREND + EMA20>EMA50 + ADX 30.0 + Pullback + Bullish Engulfing",
      "notified": true,
      "recommendation": "BUY",
      "confidence": 85.5,
      "confidence_label": "STRONG",
      "rec_reasons": [
        "EMA xếp hàng chuẩn xu hướng",
        "ADX mạnh (30.0)",
        "Giá pullback sát EMA",
        "Nến xác nhận: Bullish Engulfing",
        "RSI 58"
      ],
      "outcome": "WIN",
      "trade_plan": {
        "entry": 101.0,
        "stop_loss": 94.0,
        "take_profit": 109.4,
        "risk_reward": "1 : 1.2",
        "rr_ratio": 1.2,
        "risk_points": 7.0,
        "reward_points": 8.4,
        "risk_percent": 1.1,
        "sl_source": "swing-ATR",
        "tp_source": "structure+minRR",
        "trail_distance": 1.5,
        "risk_amount": 110.0,
        "lot_size": 0.16,
        "expected_profit": 132.0
      }
    },
    {
      "time": "2026-07-21 22:36:35",
      "candle_time": "2026-07-01 12:00:00",
      "symbol": "XAUUSD",
      "timeframe": "M30",
      "action": "SELL",
      "trend": "DOWNTREND",
      "strength": "STRONG",
      "price": 99.0,
      "ema20": 99.2,
      "ema50": 100.0,
      "ema200": 101.0,
      "adx": 30.0,
      "atr": 1.0,
      "rsi": 42.0,
      "pattern": "Bearish Engulfing",
      "reason": "HTF DOWNTREND + EMA20<EMA50 + ADX 30.0 + Pullback + Bearish Engulfing",
      "notified": true,
      "recommendation": "SELL",
      "confidence": 85.5,
      "confidence_label": "STRONG",
      "rec_reasons": [
        "EMA xếp hàng chuẩn xu hướng",
        "ADX mạnh (30.0)",
        "Giá pullback sát EMA",
        "Nến xác nhận: Bearish Engulfing",
        "RSI 42"
      ],
      "outcome": "LOSS",
      "trade_plan": {
        "entry": 99.0,
        "stop_loss": 106.0,
        "take_profit": 90.6,
        "risk_reward": "1 : 1.2",
        "rr_ratio": 1.2,
        "risk_points": 7.0,
        "reward_points": 8.4,
        "risk_percent": 1.21,
        "sl_source": "swing-ATR",
        "tp_source": "structure+minRR",
        "trail_distance": 1.5,
        "risk_amount": 121.0,
        "lot_size": 0.17,
        "expected_profit": 145.2
      }
    },
    {
      "time": "2026-07-21 22:36:35",
      "candle_time": "2026-07-01 12:00:00",
      "symbol": "EURUSD",
      "timeframe": "H1",
      "action": "NO_TRADE",
      "trend": "DOWNTREND",
      "strength": "WEAK",
      "price": 100.5,
      "ema20": 100.8,
      "ema50": 100.0,
      "ema200": 98.0,
      "adx": 30.0,
      "atr": 1.0,
      "rsi": 58.0,
      "pattern": "Bullish Engulfing",
      "reason": "Chua thuan trend lon / EMA20-50 chua xep hang",
      "notified": false,
      "recommendation": "WAIT",
      "confidence": 85.5,
      "confidence_label": "STRONG",
      "rec_reasons": [
        "EMA xếp hàng chuẩn xu hướng",
        "ADX mạnh (30.0)",
        "Giá pullback sát EMA",
        "Nến xác nhận: Bullish Engulfing",
        "RSI 58"
      ]
    }
  ]
};
